# customize to fit your situation
videodevice /dev/video0
width 640
height 480
framerate 15
threshold 1500
stream_port 8081
webcontrol_port 8080
target_dir /var/lib/motion
on_event_start /usr/local/bin/telegram_notify.sh
